version: 0.2

phases:
  build:
    commands:
      - echo "📤 Sending SNS approval request..."
      - |
        aws sns publish \
          --topic-arn arn:aws:sns:ap-south-1:856380560704:ec2-approval-topic \
          --region ap-south-1 \
          --subject "Approval Required to Stop EC2 Instance" \
          --message "Please confirm whether to stop EC2 instance i-0c94b2892a655e01e. Respond 'yes' or 'no' manually or via input to the next pipeline step."
