version: 0.2

phases:
  build:
    commands:
      - echo "Checking approval..."
      - |
        if [ "$APPROVAL" == "yes" ]; then
          echo "Stopping EC2 instance..."
          aws ec2 stop-instances --instance-ids i-0c94b2892a655e01e --region ap-south-1
        else
          echo "Approval denied. EC2 will continue running."
        fi
